name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "waka update time stats"
          SHOW_TITLE: true
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
